#!/bin/bash
# vim:fileencoding=utf-8:foldmethod=marker

# hcbin=/home/max/build/herbstluftwm-0.9.5/build/herbstclient
hcbin=/bin/herbstclient
hc() {
    $hcbin "$@"
}

hc emit_hook reload

~/.config/herbstluftwm/theme.sh

# settings: {{{

hc set frame_border_inner_width 0
hc set frame_border_outer_width 0
hc set show_frame_decoration false
hc set frame_border_width 0

hc set frame_bg_active_color '#00000000'
hc set frame_bg_normal_color '#00000000'

hc set frame_gap 0 # The gap between frames in the tiling mode. [int]
hc set window_gap 0 #Gap between windows
hc set frame_padding 0 # Gapp between windows and frames

hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0
hc set hide_covered_windows on

hc set tree_style '╾│ ├└╼─┐'
# }}} 

# keybindings: {{{

# remove all existing keybindings
hc keyunbind --all

Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close
hc keybind $Mod-Return spawn kitty
hc keybind $Mod-Shift-Return spawn kitty neofetch

# move focus in tiling and floating mode
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# move clients in tiling and floating mode
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u spawn bash -c "$hcbin split bottom 0.5 && $hcbin focus down"
hc keybind $Mod-o spawn bash -c "$hcbin split right 0.5 && $hcbin focus right"
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

tag_names=( {1..9} )
tag_names[0]="term"
tag_names[1]="www"
tag_names[2]="misc"
tag_names[3]="term"
tag_names[4]="www(2)"
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-Shift-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-space set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-d set_attr clients.focus.decorated toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle +1
hc keybind $Mod-Shift-c cycle -1

# run prompt
hc keybind $Mod+d spawn rofi -modi drun -show drun
# hc keybind $Mod+d spawn alacritty --class "alacritty-run" -e ~/.config/herbstluftwm/runmenu.sh
hc keybind $Mod+s spawn rofi -show window

# dunstctl controls
hc keybind $Mod-Shift-p spawn dunstctl history-pop
hc keybind $Mod-Shift-o spawn dunstctl close

# scratchpad
hc keybind $Mod-Control-t spawn ~/.config/herbstluftwm/q3terminal.sh

# lock screen using i3lock
hc keybind Super-Shift-semicolon spawn i3lock -c 000000

# Reload Background
hc keybind $Mod-Control-t spawn ~/.config/herbstluftwm/q3terminal.sh
hc keybind $Mod-Control-i spawn ~/.config/herbstluftwm/setwallpaper
hc keybind $Mod-Control-o spawn bash -c "~/.config/herbstluftwm/panel.sh"

hc keybind $Mod-Control-f spawn flameshot gui
# }}}

# rules: {{{
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule instance="alacritty-run" floating=on floatplacement=center floating_geometry=440x560
hc rule fixedsize floating=on

# }}}

# autostart: {{{
# set the wallpaper
# wal -wteq
# nitrogen --restore
~/.config/herbstluftwm/setwallpaper
# }}}

# monitors: {{{
# configure monitors
# herbstclient set_monitors 2560x1440+0+0 1920x1080+2560+0
# herbstclient set_monitors 2560x1440+0+0
# herbstclient set_monitors 1920x1080+0+0 2560x1440+1920+0
# herbstclient set_monitors 1920x1080+0+0
hc detect_monitors

# }}}
